name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set Git Safe Directory
      - name: Set Git Safe Directory
        run: |
          git config --global --add safe.directory /var/www/arista

      # Step 3: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}       # Server IP or domain
          username: ${{ secrets.SERVER_USER }}   # SSH username
          port: ${{ secrets.SERVER_PORT }}       # SSH port (default: 22)
          key: ${{ secrets.DEPLOY_KEY }}         # SSH private key from GitHub Secrets
          script: |
            cd /var/www/arista
            echo "Deployment directory: $(pwd)"
            # Add other deployment commands here

            # Fix permission issues and run composer install
            sudo chown -R www-data:www-data /var/www/arista
            sudo chmod -R 775 /var/www/arista/storage /var/www/arista/bootstrap/cache

            # Run composer install as www-data
            sudo -u www-data composer install --no-dev --prefer-dist
