name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create SSH Key File
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key
        chmod 600 deploy_key

    - name: Upload files to server
      run: |
        scp -r -i ${{ secrets.DEPLOY_KEY }} -P ${{ secrets.SERVER_PORT }} ./ root@${{ secrets.SERVER_HOST }}:/var/www/arista

    - name: Run deploy commands on server
      run: |
        ssh -i ${{ secrets.DEPLOY_KEY }} -p ${{ secrets.SERVER_PORT }} root@${{ secrets.SERVER_HOST }} << 'EOF'
        cd /var/www/arista
        php artisan down || true
        composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
        php artisan cache:clear
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan up
        EOF
