name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Navigate to the project directory
            cd /var/www/arista

            # Add the directory to Git's safe list
            git config --global --add safe.directory /var/www/arista

            # Reset to the latest commit
            git reset --hard HEAD

            # Pull the latest changes
            git pull origin main --no-ff

            # Set proper ownership and permissions
            sudo chown -R $USER:www-data /var/www/arista
            sudo chmod -R 775 storage bootstrap/cache

            # Install Composer dependencies
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
            composer dump-autoload

            # Laravel optimizations and cache clearing
            php artisan cache:clear
            php artisan config:cache
            php artisan config:clear
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link

            # Exit maintenance mode
            php artisan up
