name: Deploy to Server

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh root@36.64.190.85 'cd /var/www/arista && git pull origin main && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache'
