name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #cek apakah ini berhasil masuk atau tidak
      - uses: actions/checkout@v2
      - name: Deploy Code
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Starting deployment..."
            cd /var/www/html/arista && && bash .scripts/deploy.sh


