name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}       # Server IP or domain
          username: ${{ secrets.SERVER_USER }}   # SSH username
          port: ${{ secrets.SERVER_PORT }}       # SSH port (default: 22)
          key: ${{ secrets.DEPLOY_KEY }}         # SSH private key from GitHub Secrets
          script: |
            cd /var/www/arista
            # Reset to the latest commit
            git reset --hard HEAD
            # Pull the latest changes from the main branch
            git pull origin main --no-ff
            # Install Composer dependencies
            composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction
            # Dump Composer autoload
            composer dump-autoload
            # Clear and cache Laravel configurations
            php artisan cache:clear
            php artisan config:cache
            php artisan config:clear
            php artisan route:cache
            php artisan view:cache
            # Create symbolic links for storage
            php artisan storage:link
            # Exit maintenance mode
            php artisan up
