name: Deploy Apps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    # Install Composer
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    # Set up SSH key
    - name: Set up SSH key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Set permissions for necessary directories
          sudo chown -R www-data:www-data /var/www/arista
          sudo chmod -R 775 /var/www/arista

          # Enter maintenance mode if needed (e.g., Laravel)
          cd /var/www/arista && php artisan down

          # Run build as www-data (no sudo required)
          su -s /bin/bash -c "npm install" www-data
          su -s /bin/bash -c "npm run build" www-data

          # Bring the app back up after build
          cd /var/www/arista && php artisan up

          # Optionally, clear cache or optimize (depending on your application)
          su -s /bin/bash -c "php artisan optimize" www-data
