name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Menentukan branch yang akan memicu deploy (misalnya, `main`)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup PHP (sesuaikan dengan versi PHP yang digunakan dalam proyek)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Ganti dengan versi PHP yang sesuai

    # Install Composer
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    # Set up SSH key (jika menggunakan SSH untuk deploy)
    - name: Set up SSH key
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Jalankan script deploy.sh
          cd /var/www/arista/.script
          chmod +x deploy.sh
          ./deploy.sh
