name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set Git Safe Directory
      - name: Set Git Safe Directory
        run: |
          git config --global --add safe.directory /var/www/arista

      # Step 3: Deploy to server via SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}       # Server IP or domain
          username: ${{ secrets.SERVER_USER }}   # SSH username
          port: ${{ secrets.SERVER_PORT }}       # SSH port (default: 22)
          key: ${{ secrets.DEPLOY_KEY }}         # SSH private key from GitHub Secrets
          script: |
            script: "cd /var/www/arista/scripts/deploy.sh"
