name: Deploy Apps

on:
  push:
    branches:
      - main  # Menentukan branch yang akan memicu deploy (misalnya, `main`)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Setup PHP (sesuaikan dengan versi PHP yang digunakan dalam proyek)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # Ganti dengan versi PHP yang sesuai

    # Install Composer
    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar /usr/local/bin/composer

    # Set up SSH key (jika menggunakan SSH untuk deploy)
    - name: Set up SSH key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Set permissions for necessary directories
          sudo chown -R www-data:www-data /var/www/arista
          sudo chmod -R 775 /var/www/arista

          # Check if vite.config.js exists
          ls -l /var/www/arista/vite.config.js

          # Set correct permissions for storage
          sudo chown -R www-data:www-data /var/www/arista/storage
          sudo chmod -R 775 /var/www/arista/storage

          # Enter maintenance mode if needed (e.g., Laravel)
          cd /var/www/arista && php artisan down

          # Run build as www-data (to avoid permission issues)
          sudo -u www-data npm install
          sudo -u www-data npm run build

          # Bring the app back up after build
          cd /var/www/arista && php artisan up

          # Optionally, clear cache or optimize (depending on your application)
          sudo -u www-data php artisan optimize

          # Additional deployment commands (if needed)
          # Example: Restart services, clear cache, etc.
