name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup PHP (jika diperlukan)
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    # 3. Install Composer dependencies
    - name: Install dependencies with Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        mv composer.phar $HOME/.local/bin/composer
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        composer install --no-dev --optimize-autoloader

    # 4. Sync project files to server using rsync
    - name: Deploy files to server
      run: |
        rsync -avz --delete \
          -e "ssh -i $HOME/.ssh/deploy_key -p ${{ secrets.SERVER_PORT }}" \
          ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/arista

    # 5. Run deployment script on server via SSH
    - name: Run deployment script on server
      run: |
        ssh -i $HOME/.ssh/deploy_key -p ${{ secrets.SERVER_PORT }} \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "cd /var/www/arista && bash .scripts/deploy.sh"

    # 6. Clean up (opsional)
    - name: Clean up workspace
      run: |
        rm -rf $HOME/.local/bin/composer
